### ISSUE TITLE
Installation Link is broken

### ISSUE THREAD

**Issue by akwick** [restic/restic.github.io#26]
URL: https://restic.github.io/#installation
Click on Installation Instructions Page

Is: https://restic.readthedocs.io/en/stable/installation.html
`

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

`

Should: show the installation instructions (https://restic.readthedocs.io/en/stable/020_installation.html)

**Comment by fd0** [comment]
Oh, thanks for the hint!
